import express from 'express';
import db from '../database/db.js';

const router = express.Router();

// ИСПРАВЛЕНО: Добавлен try-catch
// Экспорт в JSON
router.get('/json/:runId', async (req, res) => {
  try {
    const run = db.getRun(req.params.runId);
    
    if (!run) {
      return res.status(404).json({ error: 'Run not found' });
    }

    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Content-Disposition', `attachment; filename="translation_${run.id}.json"`);
    res.send(JSON.stringify(run, null, 2));
  } catch (error) {
    console.error('Export JSON error:', error);
    res.status(500).json({ error: error.message });
  }
});

// ИСПРАВЛЕНО: Добавлен try-catch
// Экспорт в Markdown
router.get('/markdown/:runId', async (req, res) => {
  try {
    const run = db.getRun(req.params.runId);
    
    if (!run) {
      return res.status(404).json({ error: 'Run not found' });
    }

    const markdown = generateMarkdownReport(run);

    res.setHeader('Content-Type', 'text/markdown');
    res.setHeader('Content-Disposition', `attachment; filename="translation_${run.id}.md"`);
    res.send(markdown);
  } catch (error) {
    console.error('Export Markdown error:', error);
    res.status(500).json({ error: error.message });
  }
});

// Генерация Markdown отчёта
function generateMarkdownReport(run) {
  let md = `# Translation Chaos Report\n\n`;
  md += `**Run ID:** ${run.id}\n`;
  md += `**Date:** ${new Date(run.timestamp).toLocaleString()}\n`;
  md += `**Overall Drift:** ${Math.round(run.overallDrift * 100)}%\n\n`;

  md += `## Original Text\n\n`;
  md += `> ${run.originalText}\n\n`;

  md += `## Language Chain\n\n`;
  md += run.chain.join(' → ') + '\n\n';

  md += `## Step-by-Step Results\n\n`;

  run.results.forEach((step, i) => {
    if (i === 0) {
      md += `### Step 0: ${step.language} (Original)\n\n`;
      md += `${step.text}\n\n`;
    } else {
      const analysis = run.analysis[i - 1];
      md += `### Step ${i}: ${step.from} → ${step.language}\n\n`;
      md += `**Similarity:** ${Math.round(analysis.similarity * 100)}%\n\n`;
      md += `**Text:** ${step.text}\n\n`;
      
      if (analysis.changeType) {
        md += `**Change Type:** ${analysis.changeType.label}\n\n`;
      }
    }
  });

  md += `## Final Text\n\n`;
  md += `> ${run.results[run.results.length - 1].text}\n\n`;

  md += `---\n`;
  md += `*Generated by Translation Chaos Generator*\n`;

  return md;
}

export default router;