import express from 'express';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createCanvas } from 'canvas'; // npm install canvas
import db from '../database/db.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const router = express.Router();

// Экспорт в JSON
router.get('/json/:runId', async (req, res) => {
  const run = db.getRun(req.params.runId);
  
  if (!run) {
    return res.status(404).json({ error: 'Run not found' });
  }

  res.setHeader('Content-Type', 'application/json');
  res.setHeader('Content-Disposition', `attachment; filename="translation_${run.id}.json"`);
  res.send(JSON.stringify(run, null, 2));
});

// Экспорт в Markdown
router.get('/markdown/:runId', async (req, res) => {
  const run = db.getRun(req.params.runId);
  
  if (!run) {
    return res.status(404).json({ error: 'Run not found' });
  }

  const markdown = generateMarkdownReport(run);

  res.setHeader('Content-Type', 'text/markdown');
  res.setHeader('Content-Disposition', `attachment; filename="translation_${run.id}.md"`);
  res.send(markdown);
});

// Экспорт графика в PNG
router.get('/chart/:runId', async (req, res) => {
  const run = db.getRun(req.params.runId);
  
  if (!run) {
    return res.status(404).json({ error: 'Run not found' });
  }

  const canvas = createCanvas(800, 400);
  const ctx = canvas.getContext('2d');

  // Рисуем график
  drawDriftChart(ctx, run.analysis, 800, 400);

  const buffer = canvas.toBuffer('image/png');

  res.setHeader('Content-Type', 'image/png');
  res.setHeader('Content-Disposition', `attachment; filename="chart_${run.id}.png"`);
  res.send(buffer);
});

// Генерация Markdown отчёта
function generateMarkdownReport(run) {
  let md = `# Translation Chaos Report\n\n`;
  md += `**Run ID:** ${run.id}\n`;
  md += `**Date:** ${new Date(run.timestamp).toLocaleString()}\n`;
  md += `**Overall Drift:** ${Math.round((1 - run.analysis[run.analysis.length - 1].similarity) * 100)}%\n\n`;

  md += `## Original Text\n\n`;
  md += `> ${run.originalText}\n\n`;

  md += `## Language Chain\n\n`;
  md += run.chain.join(' → ') + '\n\n';

  md += `## Step-by-Step Results\n\n`;

  run.results.forEach((step, i) => {
    if (i === 0) {
      md += `### Step 0: ${step.language} (Original)\n\n`;
      md += `${step.text}\n\n`;
    } else {
      const analysis = run.analysis[i - 1];
      md += `### Step ${i}: ${step.from} → ${step.language}\n\n`;
      md += `**Similarity:** ${Math.round(analysis.similarity * 100)}%\n\n`;
      md += `**Text:** ${step.text}\n\n`;
      
      if (analysis.changeType) {
        md += `**Change Type:** ${analysis.changeType.icon} ${analysis.changeType.label}\n\n`;
      }
    }
  });

  md += `## Final Text\n\n`;
  md += `> ${run.results[run.results.length - 1].text}\n\n`;

  md += `---\n`;
  md += `*Generated by Translation Chaos Generator*\n`;

  return md;
}

// Рисование графика на canvas
function drawDriftChart(ctx, analysis, width, height) {
  const padding = 40;
  const chartWidth = width - padding * 2;
  const chartHeight = height - padding * 2;

  // Фон
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, width, height);

  // Оси
  ctx.strokeStyle = '#333';
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.moveTo(padding, padding);
  ctx.lineTo(padding, height - padding);
  ctx.lineTo(width - padding, height - padding);
  ctx.stroke();

  // Данные
  const data = [1, ...analysis.map(a => a.similarity)];
  const stepWidth = chartWidth / (data.length - 1);

  // Линия графика
  ctx.strokeStyle = '#667eea';
  ctx.lineWidth = 3;
  ctx.beginPath();

  data.forEach((value, i) => {
    const x = padding + i * stepWidth;
    const y = height - padding - (value * chartHeight);
    
    if (i === 0) {
      ctx.moveTo(x, y);
    } else {
      ctx.lineTo(x, y);
    }
  });

  ctx.stroke();

  // Точки
  data.forEach((value, i) => {
    const x = padding + i * stepWidth;
    const y = height - padding - (value * chartHeight);
    
    ctx.fillStyle = value > 0.85 ? '#4caf50' : (value > 0.70 ? '#ff9800' : '#f44336');
    ctx.beginPath();
    ctx.arc(x, y, 5, 0, Math.PI * 2);
    ctx.fill();
  });

  // Заголовок
  ctx.fillStyle = '#333';
  ctx.font = 'bold 16px Arial';
  ctx.fillText('Semantic Drift Chart', padding, 20);
}

export default router;